version: "2"
services:
  database:
    container_name: database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  server:
    container_name: server
    restart: always
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    expose:
      - ${APP_SERVER_PORT}
    environment:
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      API_HOST: ${API_HOST}
    links:
      - mongo
  ember:
    image: danlynn/ember-cli:3.0.0
    environment:
      CI: "true"
      EMBER_APP_PORT: ${EMBER_APP_PORT}
    volumes:
      - ./frontend:/myapp
      - .bash_history:/root/.bash_history
      - ./frontend/node_modules:/myapp/node_modules
    tmpfs:
      - /myapp/tmp
    expose:
      - ${EMBER_APP_PORT}
    ports:
      - ${EMBER_APP_PORT}:${EMBER_APP_PORT}
      - "7020:7020"
      - "7357:7357"
